{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6a651f81-5b13-4729-a9cb-104d201fa775",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: plotly in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (5.24.1)\n",
      "Collecting dash\n",
      "  Downloading dash-3.2.0-py3-none-any.whl.metadata (10 kB)\n",
      "Requirement already satisfied: tenacity>=6.2.0 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from plotly) (9.0.0)\n",
      "Requirement already satisfied: packaging in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from plotly) (24.2)\n",
      "Requirement already satisfied: Flask<3.2,>=1.0.4 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from dash) (3.1.0)\n",
      "Requirement already satisfied: Werkzeug<3.2 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from dash) (3.1.3)\n",
      "Requirement already satisfied: importlib-metadata in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from dash) (8.5.0)\n",
      "Requirement already satisfied: typing-extensions>=4.1.1 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from dash) (4.12.2)\n",
      "Requirement already satisfied: requests in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from dash) (2.32.3)\n",
      "Collecting retrying (from dash)\n",
      "  Downloading retrying-1.4.2-py3-none-any.whl.metadata (5.5 kB)\n",
      "Requirement already satisfied: nest-asyncio in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from dash) (1.6.0)\n",
      "Requirement already satisfied: setuptools in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from dash) (72.1.0)\n",
      "Requirement already satisfied: Jinja2>=3.1.2 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from Flask<3.2,>=1.0.4->dash) (3.1.6)\n",
      "Requirement already satisfied: itsdangerous>=2.2 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from Flask<3.2,>=1.0.4->dash) (2.2.0)\n",
      "Requirement already satisfied: click>=8.1.3 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from Flask<3.2,>=1.0.4->dash) (8.1.8)\n",
      "Requirement already satisfied: blinker>=1.9 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from Flask<3.2,>=1.0.4->dash) (1.9.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from Werkzeug<3.2->dash) (3.0.2)\n",
      "Requirement already satisfied: zipp>=3.20 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from importlib-metadata->dash) (3.21.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from requests->dash) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from requests->dash) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from requests->dash) (2.3.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages (from requests->dash) (2025.6.15)\n",
      "Downloading dash-3.2.0-py3-none-any.whl (7.9 MB)\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m7.9/7.9 MB\u001b[0m \u001b[31m18.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m MB/s\u001b[0m eta \u001b[36m0:00:01\u001b[0m\n",
      "Downloading retrying-1.4.2-py3-none-any.whl (10 kB)\n",
      "Installing collected packages: retrying, dash\n",
      "\u001b[2K   \u001b[38;2;114;156;31m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2/2\u001b[0m [dash]\n",
      "\u001b[1A\u001b[2KSuccessfully installed dash-3.2.0 retrying-1.4.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install plotly dash"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "56d1159e-432d-4ee0-a979-0fb3a14abc1a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash app running on http://127.0.0.1:8050/\n"
     ]
    },
    {
     "data": {
      "application/javascript": [
       "window.open('http://127.0.0.1:8050/')"
      ],
      "text/plain": [
       "<IPython.core.display.Javascript object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[2025-08-30 22:03:56,644] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/dash.py\", line 1494, in dispatch\n",
      "    response_data = ctx.run(partial_func)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 688, in add_context\n",
      "    raise err\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 679, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 59, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/d1/z_5c5v3j7zv03b8hsw25h3bm0000gn/T/ipykernel_80579/3431810105.py\", line 160, in move_window\n",
      "    ctx = dash.ctx.triggered_id if hasattr(dash, \"ctx\") else None\n",
      "                                           ^^^^\n",
      "NameError: name 'dash' is not defined. Did you mean: 'Dash'?\n",
      "[2025-08-30 22:05:53,261] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/dash.py\", line 1494, in dispatch\n",
      "    response_data = ctx.run(partial_func)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 688, in add_context\n",
      "    raise err\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 679, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 59, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/d1/z_5c5v3j7zv03b8hsw25h3bm0000gn/T/ipykernel_80579/3431810105.py\", line 160, in move_window\n",
      "    ctx = dash.ctx.triggered_id if hasattr(dash, \"ctx\") else None\n",
      "                                           ^^^^\n",
      "NameError: name 'dash' is not defined. Did you mean: 'Dash'?\n",
      "[2025-08-30 22:05:53,370] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/dash.py\", line 1494, in dispatch\n",
      "    response_data = ctx.run(partial_func)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 688, in add_context\n",
      "    raise err\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 679, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 59, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/d1/z_5c5v3j7zv03b8hsw25h3bm0000gn/T/ipykernel_80579/3431810105.py\", line 160, in move_window\n",
      "    ctx = dash.ctx.triggered_id if hasattr(dash, \"ctx\") else None\n",
      "                                           ^^^^\n",
      "NameError: name 'dash' is not defined. Did you mean: 'Dash'?\n",
      "[2025-08-30 22:06:03,968] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/dash.py\", line 1494, in dispatch\n",
      "    response_data = ctx.run(partial_func)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 688, in add_context\n",
      "    raise err\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 679, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 59, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/d1/z_5c5v3j7zv03b8hsw25h3bm0000gn/T/ipykernel_80579/3431810105.py\", line 160, in move_window\n",
      "    ctx = dash.ctx.triggered_id if hasattr(dash, \"ctx\") else None\n",
      "                                           ^^^^\n",
      "NameError: name 'dash' is not defined. Did you mean: 'Dash'?\n",
      "[2025-08-30 22:06:04,081] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/dash.py\", line 1494, in dispatch\n",
      "    response_data = ctx.run(partial_func)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 688, in add_context\n",
      "    raise err\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 679, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 59, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/d1/z_5c5v3j7zv03b8hsw25h3bm0000gn/T/ipykernel_80579/3431810105.py\", line 160, in move_window\n",
      "    ctx = dash.ctx.triggered_id if hasattr(dash, \"ctx\") else None\n",
      "                                           ^^^^\n",
      "NameError: name 'dash' is not defined. Did you mean: 'Dash'?\n",
      "[2025-08-30 22:06:06,527] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 1511, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 919, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 917, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/flask/app.py\", line 902, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]\n",
      "           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/dash.py\", line 1494, in dispatch\n",
      "    response_data = ctx.run(partial_func)\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 688, in add_context\n",
      "    raise err\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 679, in add_context\n",
      "    output_value = _invoke_callback(func, *func_args, **func_kwargs)  # type: ignore[reportArgumentType]\n",
      "  File \"/Users/arsalansharifizad/anaconda3/lib/python3.13/site-packages/dash/_callback.py\", line 59, in _invoke_callback\n",
      "    return func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/var/folders/d1/z_5c5v3j7zv03b8hsw25h3bm0000gn/T/ipykernel_80579/3431810105.py\", line 160, in move_window\n",
      "    ctx = dash.ctx.triggered_id if hasattr(dash, \"ctx\") else None\n",
      "                                           ^^^^\n",
      "NameError: name 'dash' is not defined. Did you mean: 'Dash'?\n"
     ]
    }
   ],
   "source": [
    "# these are the UI comps, and libaries \n",
    "from dash import Dash, html, dcc, dash_table, callback, Input, Output, State\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "\n",
    "# shows the program our csv we have aloocated\n",
    "CSV_PATH = \"gyro_data.csv\" \n",
    "\n",
    "# loading our column and data and showing error if csv path is wrong\n",
    "def load_gyro_csv(csv_path: str) -> pd.DataFrame:\n",
    "    if not Path(csv_path).exists():\n",
    "        raise FileNotFoundError(f\":CSV wasn't found {csv_path}\")\n",
    "\n",
    "    df = pd.read_csv(csv_path)\n",
    "\n",
    "    #detect timestamp col\n",
    "    ts_candidates = [\"timestamp_iso\",\"timestamp\",\"time\",\"datetime\",\"ts\"]\n",
    "    ts_col = next((c for c in ts_candidates if c in df.columns), None)\n",
    "    if ts_col:\n",
    "        df[ts_col] = pd.to_datetime(df[ts_col], errors=\"coerce\")\n",
    "\n",
    "    # Normalizes our data columns to gx, gy, gz\n",
    "    rename_map_options = [\n",
    "        {\"gx_dps\":\"gx\",\"gy_dps\":\"gy\",\"gz_dps\":\"gz\"},\n",
    "        {\"x\":\"gx\",\"y\":\"gy\",\"z\":\"gz\"},\n",
    "        {\"gx\":\"gx\",\"gy\":\"gy\",\"gz\":\"gz\"},\n",
    "        {\"gyro_x\":\"gx\",\"gyro_y\":\"gy\",\"gyro_z\":\"gz\"},\n",
    "        {\"x_dps\":\"gx\",\"y_dps\":\"gy\",\"z_dps\":\"gz\"},\n",
    "    ]\n",
    "    for mapping in rename_map_options:\n",
    "        if all(src in df.columns for src in mapping.keys()):\n",
    "            df = df.rename(columns=mapping)\n",
    "            break\n",
    "\n",
    "    # coerce to numeric, bad values become NaN\n",
    "    for c in [\"gx\",\"gy\",\"gz\"]:\n",
    "        if c in df.columns:\n",
    "            df[c] = pd.to_numeric(df[c], errors=\"coerce\")\n",
    "\n",
    "    # last checking to make sure we have our data before proceeding\n",
    "    missing = [c for c in [\"gx\",\"gy\",\"gz\"] if c not in df.columns]\n",
    "    if missing:\n",
    "        raise ValueError(\n",
    "            f\"Could not find gyro columns. Need any of these schemas: \"\n",
    "            f\"(gx_dps,gy_dps,gz_dps) or (x,y,z). Missing: {missing}\"\n",
    "        )\n",
    "\n",
    "    # Dropping the rows with no gyro readings (NaN)\n",
    "    df = df.dropna(subset=[\"gx\",\"gy\",\"gz\"]).reset_index(drop=True)\n",
    "    return df, ts_col\n",
    "\n",
    "df, TS_COL = load_gyro_csv(CSV_PATH)\n",
    "\n",
    "# UI layout\n",
    "app = Dash(__name__)\n",
    "app.title = \"Gyroscope Dashboard\"\n",
    "\n",
    "GRAPH_TYPES = [\n",
    "    {\"label\":\"Line\",\"value\":\"line\"},\n",
    "    {\"label\":\"Scatter\",\"value\":\"scatter\"},\n",
    "    {\"label\":\"Histogram (distribution)\",\"value\":\"hist\"},\n",
    "    {\"label\":\"Box (distribution)\",\"value\":\"box\"},\n",
    "    {\"label\":\"Violin (distribution)\",\"value\":\"violin\"},\n",
    "]\n",
    "VAR_OPTIONS = [\n",
    "    {\"label\":\"X\",\"value\":\"gx\"},\n",
    "    {\"label\":\"Y\",\"value\":\"gy\"},\n",
    "    {\"label\":\"Z\",\"value\":\"gz\"},\n",
    "]\n",
    "\n",
    "def kpi_table(window_df: pd.DataFrame, vars_sel: list[str]) -> pd.DataFrame:\n",
    "    # makes a compact summary\n",
    "    stats = {}\n",
    "    for v in vars_sel:\n",
    "        s = window_df[v].dropna()\n",
    "        if s.empty:\n",
    "            continue\n",
    "        stats[v] = {\n",
    "            \"count\": int(s.count()),\n",
    "            \"mean\":  float(s.mean()),\n",
    "            \"std\":   float(s.std(ddof=1)) if s.count() > 1 else 0.0,\n",
    "            \"min\":   float(s.min()),\n",
    "            \"median\":float(s.median()),\n",
    "            \"max\":   float(s.max()),\n",
    "            \"rms\":   float(np.sqrt(np.mean(np.square(s)))),\n",
    "        }\n",
    "    return pd.DataFrame.from_dict(stats, orient=\"index\").round(4).reset_index(names=\"variable\")\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H3(\"Gyroscope CSV - data handler\"),\n",
    "    html.Div([\n",
    "        html.Div([\n",
    "            html.Label(\"Chart type\"),\n",
    "            dcc.Dropdown(id=\"graph-type\", options=GRAPH_TYPES, value=\"line\", clearable=False),\n",
    "        ], style={\"width\":\"20%\", \"minWidth\":\"180px\"}),\n",
    "\n",
    "        html.Div([\n",
    "            html.Label(\"Variables\"),\n",
    "            dcc.Dropdown(id=\"vars\", options=VAR_OPTIONS,\n",
    "                         value=[\"gx\",\"gy\",\"gz\"], multi=True, clearable=False),\n",
    "        ], style={\"width\":\"30%\", \"minWidth\":\"240px\"}),\n",
    "\n",
    "        html.Div([\n",
    "            html.Label(\"Samples per page (N)\"),\n",
    "            dcc.Input(id=\"num-samples\", type=\"number\", value=1000, min=10, step=10, debounce=True,\n",
    "                      style={\"width\":\"100%\"}),\n",
    "        ], style={\"width\":\"18%\", \"minWidth\":\"160px\"}),\n",
    "\n",
    "        html.Div([\n",
    "            html.Label(\"Navigation\"),\n",
    "            html.Div([\n",
    "                html.Button(\"◀ Prev\", id=\"prev-btn\", n_clicks=0),\n",
    "                html.Button(\"Next ▶\", id=\"next-btn\", n_clicks=0, style={\"marginLeft\":\"8px\"}),\n",
    "            ]),\n",
    "        ], style={\"width\":\"20%\", \"minWidth\":\"180px\"}),\n",
    "\n",
    "    ], style={\"display\":\"flex\", \"gap\":\"12px\", \"flexWrap\":\"wrap\"}),\n",
    "\n",
    "    # Store for window position (start index)\n",
    "    dcc.Store(id=\"win-start\", data=0),\n",
    "\n",
    "    html.Hr(),\n",
    "\n",
    "    dcc.Graph(id=\"gyro-graph\"),\n",
    "\n",
    "    html.H4(\"Data Summary\"),\n",
    "    dash_table.DataTable(\n",
    "        id=\"summary\",\n",
    "        page_size=6,\n",
    "        style_table={\"overflowX\":\"auto\"},\n",
    "        style_cell={\"textAlign\":\"center\",\"padding\":\"6px\"},\n",
    "        style_header={\"fontWeight\":\"bold\"}\n",
    "    ),\n",
    "\n",
    "    html.H4(\"Current window, Raw rows\"),\n",
    "    dash_table.DataTable(\n",
    "        id=\"raw\",\n",
    "        page_size=12,\n",
    "        style_table={\"overflowX\":\"auto\"},\n",
    "    ),\n",
    "])\n",
    "\n",
    "# updates by either using the nav window or the sample per page(N) \n",
    "@callback(\n",
    "    Output(\"win-start\",\"data\"),\n",
    "    Input(\"prev-btn\",\"n_clicks\"),\n",
    "    Input(\"next-btn\",\"n_clicks\"),\n",
    "    Input(\"num-samples\",\"value\"),\n",
    "    State(\"win-start\",\"data\"),\n",
    "    prevent_initial_call=False\n",
    ")\n",
    "def move_window(n_prev, n_next, n, start):\n",
    "    total = len(df)\n",
    "    n = int(n) if (n and n>0) else total\n",
    "    # (next - prev) * n\n",
    "    ctx = dash.ctx.triggered_id if hasattr(dash, \"ctx\") else None\n",
    "    start = int(start or 0)\n",
    "\n",
    "    if ctx == \"next-btn\":\n",
    "        start += n\n",
    "    elif ctx == \"prev-btn\":\n",
    "        start -= n\n",
    "    else:\n",
    "        # num-samples changed or first load -> clamp start\n",
    "        pass\n",
    "\n",
    "    # Clamp\n",
    "    start = max(0, min(start, max(0, total - n)))\n",
    "    return start\n",
    "\n",
    "# builds a figure for current tables n rows \n",
    "@callback(\n",
    "    Output(\"gyro-graph\",\"figure\"),\n",
    "    Output(\"summary\",\"data\"),\n",
    "    Output(\"summary\",\"columns\"),\n",
    "    Output(\"raw\",\"data\"),\n",
    "    Output(\"raw\",\"columns\"),\n",
    "    Input(\"graph-type\",\"value\"),\n",
    "    Input(\"vars\",\"value\"),\n",
    "    Input(\"num-samples\",\"value\"),\n",
    "    Input(\"win-start\",\"data\"),\n",
    ")\n",
    "def update_view(gtype, vars_sel, n, start):\n",
    "    vars_sel = [v for v in (vars_sel or []) if v in [\"gx\",\"gy\",\"gz\"]]\n",
    "    if not vars_sel:\n",
    "        vars_sel = [\"gx\",\"gy\",\"gz\"]\n",
    "\n",
    "    total = len(df)\n",
    "    n = int(n) if (n and n>0) else total\n",
    "    start = int(start or 0)\n",
    "    end = min(start + n, total)\n",
    "\n",
    "    window = df.iloc[start:end].copy()\n",
    "\n",
    "    # for x axis timestamp if we have one, use sample index if timestamp wasnt found\n",
    "    if TS_COL and TS_COL in window.columns:\n",
    "        xaxis = window[TS_COL]\n",
    "        x_label = TS_COL\n",
    "    else:\n",
    "        xaxis = window.index\n",
    "        x_label = \"sample_index\"\n",
    "\n",
    "    # building our figure with the requested data respectivly \n",
    "    if gtype in [\"line\",\"scatter\"]:\n",
    "        # Long form for multiple traces keeping the webGL responsive\n",
    "        plot_df = window[[*vars_sel]].copy()\n",
    "        plot_df[x_label] = xaxis\n",
    "        plot_long = plot_df.melt(id_vars=[x_label], value_vars=vars_sel,\n",
    "                                 var_name=\"axis\", value_name=\"value\")\n",
    "        if gtype == \"line\":\n",
    "            fig = px.line(plot_long, x=x_label, y=\"value\", color=\"axis\",\n",
    "                          render_mode=\"webgl\" if len(plot_long)>2000 else \"auto\",\n",
    "                          title=f\"{gtype.title()} — {', '.join(vars_sel)}\")\n",
    "        else:\n",
    "            fig = px.scatter(plot_long, x=x_label, y=\"value\", color=\"axis\",\n",
    "                             render_mode=\"webgl\" if len(plot_long)>2000 else \"auto\",\n",
    "                             title=f\"Scatter — {', '.join(vars_sel)}\")\n",
    "\n",
    "        fig.update_layout(xaxis_title=x_label, yaxis_title=\"dps (deg/sec)\")\n",
    "    elif gtype in [\"hist\",\"box\",\"violin\"]:\n",
    "        # Distribution plots\n",
    "        plot_long = window[vars_sel].copy().rename(columns={\"gx\":\"X\",\"gy\":\"Y\",\"gz\":\"Z\"})\n",
    "        long = plot_long.melt(var_name=\"axis\", value_name=\"value\")\n",
    "        if gtype == \"hist\":\n",
    "            fig = px.histogram(long, x=\"value\", color=\"axis\", barmode=\"overlay\",\n",
    "                               nbins=60, opacity=0.65, title=\"Histogram\")\n",
    "            fig.update_layout(xaxis_title=\"dps (deg/sec)\", yaxis_title=\"count\")\n",
    "        elif gtype == \"box\":\n",
    "            fig = px.box(long, x=\"axis\", y=\"value\", points=\"outliers\", title=\"Box plot\")\n",
    "            fig.update_layout(yaxis_title=\"dps (deg/sec)\", xaxis_title=\"axis\")\n",
    "        else:\n",
    "            fig = px.violin(long, x=\"axis\", y=\"value\", box=True, points=\"outliers\",\n",
    "                            title=\"Violin plot\")\n",
    "            fig.update_layout(yaxis_title=\"dps (deg/sec)\", xaxis_title=\"axis\")\n",
    "    #fall back if it fails        \n",
    "    else:\n",
    "        fig = px.line(title=\"(unknown graph type)\")\n",
    "\n",
    "    # current table summary\n",
    "    summary_df = kpi_table(window, vars_sel)\n",
    "    sum_cols = [{\"name\": c, \"id\": c} for c in summary_df.columns]\n",
    "\n",
    "    # shows timestamp raw table\n",
    "    show_cols = [TS_COL] if TS_COL else []\n",
    "    show_cols += vars_sel\n",
    "    raw_df = window[show_cols].copy()\n",
    "    raw_cols = [{\"name\": c, \"id\": c} for c in raw_df.columns]\n",
    "    # returns the plot, summary \n",
    "    return fig, summary_df.to_dict(\"records\"), sum_cols, raw_df.to_dict(\"records\"), raw_cols\n",
    "\n",
    "# runs in html format and not in jupyter\n",
    "app.run(jupyter_mode=\"tab\", debug=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "916484e3-9430-4e55-950c-598755792551",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
